spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/wsb2023
    username: postgres
    password: "!Boysen2015"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: languages/messages
    encoding: UTF-8
    fallback-to-system-locale: true
  thymeleaf:
    encoding: UTF-8

